apiVersion: v1
kind: Pod
mettadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multi-container-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux:9
    image: almalinux:9
    # command: ["sleep", "1000"] 

