apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
# type of the data we are providing
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE="